### ISSUE TITLE
Image can't be displayed 

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Coursera_IBM_Data_Science#1]
Display [image](https://github.com/chandrikadeb7/Coursera_IBM_Data_Science/blob/master/Data-Science-Methodology/Week%201/Lecture%20PDFs/Screen%20Shot%202020-03-21%20at%2010.32.53%20AM.png ) in [File](https://github.com/chandrikadeb7/Coursera_IBM_Data_Science/blob/master/Data-Science-Methodology/Week%201/Lecture%20PDFs/Introduction%20to%20CRISP-DM.ipynb)

**Comment by iamsonukushwaha** [comment]
I have fixed this 

will create a pull request soon

**Comment by iamsonukushwaha** [comment]
Fixed it #2
